FROM ubuntu:latest
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install openjdk-8-jdk wget
RUN mkdir /usr/local/tomcat
RUN wget https://downloads.apache.org/tomcat/tomcat-9/v9.0.41/bin/apache-tomcat-9.0.41.tar.gz
RUN tar -xvfz apache-tomcat-9.0.41.tar.gz
RUN cp -Rv /tmp/apache-tomcat-9.0.41/* /usr/local/tomcat/
EXPOSE 8086
CMD /usr/local/tomcat/bin/catalina.sh run
